name: KryIslands
main: com.nktfh100.KryIslands.main.KryIslands
author: nktfh100
version: 1.0
api-version: 1.16
depend: [FastAsyncWorldEdit]
load: STARTUP

commands:
   ks:
      description: Main KryIslands command
